### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shri142**
Added about some attacks and basic tips to prevent ourselves from hackers.

### CODE REVIEW

**Comment by Rijubadhan** [comment]
sari142

**Comment by Rijubadhan** [comment]
You can hack wifi password with UK /US VPN

**Comment by Rijubadhan** [comment]
You want to see

**Review by Morra1 — APPROVED** [review]

**Comment by torriz** [comment]
Do you know what this repo is for? @shri142 
It's not Microsoft support faq you know..

**Review by torriz — CHANGES_REQUESTED** [review]
Not useful

**Review by Nationzaa — APPROVED** [review]

**Comment by Doobli** [comment]
how i start penetration testing

**Review by Technetium1 — COMMENTED** [review]
No. This is not good.

**Review by its0x08 — APPROVED** [review]

**Comment by Chan9390** [comment]
The PR is not an awesome list.

**Pull request closed without merging**
