### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samanL33T**
Added Awesome Mainframe Hacking

### CODE REVIEW

**Comment by hakoo361** [comment]
### how to hack Facebook code

**Comment by jesusvazque** [comment]
Cony Zacariaz

**Comment by jesusvazque** [comment]
Hola que asíendo flakita es rmosa linda bonita

**Comment by Chan9390** [comment]
Thank you for the contribution !

**Comment by ronhUs-busrur-7tuxfo** [comment]
Always, I will have to get on my desktop tomorrow to update my readme. Goodnight everyone

**Pull request merged**
