### PR TITLE
add osx security awesome

### PR DESCRIPTION
**Pull request by kai5263499**
Another list of OSX/macOS/iOS security resources

### CODE REVIEW

**Comment by Chan9390** [comment]
The list looks cool but needs some formatting.

**Comment by kai5263499** [comment]
What formatting do you think needs to be added?

**Comment by Chan9390** [comment]
Arrange in an order. Some has description, and some doesnt. It would be better if it looks uniform.

**Comment by malamel** [comment]
Done

**Comment by Chan9390** [comment]
Closing the PR as of now. If you arrange the items in the README file, then reopen this PR as it would be great to have it in this Awesome Hacking list.

**Pull request closed without merging**
