### PR TITLE
Suggestion to add iSpy to `Awesome Repositories` list.

### PR DESCRIPTION
**Pull request by Dashbloxx**
This is a pull request to add iSpy (A project I made) to the Awesome Repositories list.

### CODE REVIEW

**Comment by AnadyaNair** [comment]
What is an open port and how will iSpy scan them?

**Review by AnadyaNair — COMMENTED** [review]
What is an open port and how will iSpy scan them?

**Comment by Dashbloxx** [comment]
An open port is a port that can be connected to, and iSpy will connect to them by quickly establishing a TCP connection to it.

**Comment by AnadyaNair** [comment]
Impressive work!

**Comment by brianmccrory29** [comment]
?????

**Comment by Chan9390** [comment]
iSpy is not an awesome list nor does it seem to do anything ground breaking (comparing to nmap or zmap). Closing the PR.

**Review by Hacker1X420 — APPROVED** [review]

**Review by Hacker1X420 — APPROVED** [review]
HackerX4

**Pull request closed without merging**
