### PR TITLE
Smart hacking

### PR DESCRIPTION
**Pull request by ahmadjaniyyyy**
android hacking awesom

### CODE REVIEW

**Comment by ahmadjaniyyyy** [comment]
Awesome trick Android  hacking

**Comment by Saifullam** [comment]
I am saifullah, i do tha  facebook haking. can you help me

**Comment by ahmadjaniyyyy** [comment]
Ok

**Comment by rocky327** [comment]
can anyone please help me.
I bind apk through spynote.
whenever i install ,it installs two separate apk
and have to install 2 apps in the single Rat file.
i want to bind it in such a way so that it installed as single apk with single installation

**Comment by Saifullam** [comment]
help me,, my con: whatsapp no 01623475831

**Comment by torriz** [comment]
wtf did you approve?

**Pull request closed without merging**
