### PR TITLE
Add awesome-yara

### PR DESCRIPTION
**Pull request by rshipp**
https://github.com/InQuest/awesome-yara, for awesome [YARA](https://virustotal.github.io/yara/) resources :smile:

### CODE REVIEW

**Comment by Chan9390** [comment]
Hey @rshipp , Thanks for your contribution.

**Comment by Chan9390** [comment]
Just tweeted about the repository.
https://twitter.com/HackwithGithub/status/921242216714027009

**Comment by rshipp** [comment]
Thanks!

**Comment by Katmando32** [comment]
Yo who ever this is why and I mean why d u keep clogging my in-box up...
If you're so clever shawley u can see I'm being used as a host and have no idea what u lot are doing...

**Pull request merged**
