### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeyintminthuhtut**
Added Awesome Red Teaming Resources.

It is a live resources and will update regularly with latest Adversarial Tactics and Techniques.

### CODE REVIEW

**Comment by billyjoebaron** [comment]
Howd you run across me? Appreciate the links and the heads up on the shinys repo.

**Comment by billyjoebaron** [comment]
Right on man thanks for the heads up on the resources, repos and all around
shinys collection.  Howdnyou come across me? If youbsontnmind me asking was
that you that remoted into my LAN last night? No harm done at least not
that Ive found yet. Hit me back Im curious and always ready to learn
something new.

**Comment by Chan9390** [comment]
Hey @yeyintminthuhtut Thanks for the PR. Looks interesting. Before merging it to the master, could you format and remove the unwanted bullet points in the readme ?

**Comment by yeyintminthuhtut** [comment]
Hi @Chan9390 
I removed. Thanks :)

**Pull request merged**
