### PR TITLE
Added CyberChef

### PR DESCRIPTION
**Pull request by LucEast**
# CyberChef - The Cyber Swiss Army Knife

A simple, intuitive web app for analysing and decoding data without having to deal with complex tools or programming languages. CyberChef encourages both technical and non-technical people to explore data formats, encryption and compression.

### CODE REVIEW

**Review by juliohora91 — APPROVED** [review]

**Comment by PedroH76** [comment]
> # CyberChef - The Cyber Swiss Army Knife
> 
> A simple, intuitive web app for analysing and decoding data without having to deal with complex tools or programming languages. CyberChef encourages both technical and non-technical people to explore data formats, encryption and compression.

https://www.facebook.com/angelica.utrerasantiago

**Comment by Chan9390** [comment]
@LucEast this is not an Awesome list. Mind adding it under Other Useful Repositories section?

**Comment by LucEast** [comment]
@Chan9390 I don't mind. :)

**Review by Auto-Engineers — APPROVED** [review]

**Review by Femida666 — APPROVED** [review]

**Review by devilish66694 — APPROVED** [review]

**Comment by Auto-Engineers** [comment]
🥳

**Review by devilish66694 — COMMENTED** [review]
[[0009-non-helium-hotspots.md](https://github.com/user-attachments/files/15890901/0009-non-helium-hotspots.md)
](url)

>                  +------+
                 |      |
     +-----------+  A   |
     |           |      |
     |           +------+
     |
+------+
|      |
|  F   |
|      |
+------+
    |            +------+
    |            |      |
    |            |  B   |
    |            |      |
    |            +------+            +------+
+------+             |               |      |
|      |             |               |  C   |
|  E   +-----------------------------+      |
|      |             |               +------+
+------+             |
    |                |
    |             +------+
    |             |      |
    +-------------+  D   |
                  |      |
                  +------+

**Review by Mahmoud198425 — APPROVED** [review]

**Review by reverseittosender — APPROVED** [review]

**Pull request closed without merging**
